name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt update
    - run: sudo apt install -y ninja-build clang
    - uses: actions/checkout@v3
    - run: cmake --workflow --preset default
      env:
        CMAKE_C_COMPILER: clang
        CMAKE_CXX_COMPILER: clang++
